## Exercise 6 - Numpy

1 Generate two NumPy arrays so that first array has integers from 10 to 40 (inclusive). Second array should have integers from 220 to 250 (inclusive). Sum these arrays and present the result array.

In [7]:
import numpy as np
import sys

lst1 = np.arange(10,41)
lst2 = np.arange(220,251)


def sum_arrays(arr1,arr2):
    print("Sum {} and {}".format(arr1,arr2))
    print("Result: {}\n".format(arr1 + arr2))

sum_arrays(lst1,lst2)

Sum [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40] and [220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237
 238 239 240 241 242 243 244 245 246 247 248 249 250]
Result: [230 232 234 236 238 240 242 244 246 248 250 252 254 256 258 260 262 264
 266 268 270 272 274 276 278 280 282 284 286 288 290]



2 Generate two-dimensional array with 10 rows and 7 columns containing integers starting from 100.

In [38]:
array = np.arange(100,170).reshape(10,7)

array

array([[100, 101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112, 113],
       [114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127],
       [128, 129, 130, 131, 132, 133, 134],
       [135, 136, 137, 138, 139, 140, 141],
       [142, 143, 144, 145, 146, 147, 148],
       [149, 150, 151, 152, 153, 154, 155],
       [156, 157, 158, 159, 160, 161, 162],
       [163, 164, 165, 166, 167, 168, 169]])

3 Generate two one-dimensional arrays having integers between 1-50. First array should have even and second array should have odd numbers. Finally multiply each element from corresponding index positions from these two arrays for the result array. For example [(1 x 2),(3 x 4),(5 x 6),(7 x 8)...].

In [111]:
lst_even = np.arange(1,51)
lst_even = lst_even[lst_even%2==0].reshape(5,5)
lst_odd = np.arange(1,51,2).reshape(5,5)
lst_odd
print("Even numbers {} ".format(lst_even))
print("Odd numbers {} ".format(lst_odd))
np.multiply(lst_even,lst_odd)


Even numbers [[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]] 
Odd numbers [[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]] 


array([[   2,   12,   30,   56,   90],
       [ 132,  182,  240,  306,  380],
       [ 462,  552,  650,  756,  870],
       [ 992, 1122, 1260, 1406, 1560],
       [1722, 1892, 2070, 2256, 2450]])

4 Generate two-dimensional array (40 rows, 5 columns) containing random integers between 1 and 1000. Filter the result array so that only numbers divisable with numbers 2 and 5 are presented (number must be divisable with both).

In [139]:
num_arr = np.random.randint(1,1000,200).reshape(40,5)
query = np.where((num_arr % 2 == 0) & (num_arr % 5 == 0))
result = num_arr[query]
result


array([820, 740,  70, 680, 880, 890, 430, 550, 740, 380, 590, 630, 850,
       190, 810, 460, 670,  20, 940, 530])